query getPingerStats(
  $category: String!
  $type: String!
  $price_min: Int!
  $price_max: Int!
  $region: [String!]!
  $rooms_min: Int
  $rooms_max: Int
  $area_m2_min: Int
  $area_m2_max: Int
  $published_at_start: String!
  $published_at_end: String!
) {
  properties(
    filter: {
      category: { eq: $category }
      type: { eq: $type }
      region: { in: $region }
      price: {
        gte: $price_min
        lte: $price_max
      }
      rooms: {
        gte: $rooms_min
        lte: $rooms_max
      }
      area: {
        gte: $area_m2_min
        lte: $area_m2_max
      }
      published_at: {
        gte: $published_at_start
        lt: $published_at_end
      }
    }
  ) {
    summary {
      count
    }
  }
}
